[default.extend-words]
NED = "NED"

[default]
extend-ignore-identifiers-re = [
    # Ignore mirror hard disk names
    "2RW103_ZL2*",
    # Ignore "typos" in nftables config
    "iif", "oif",
    # NTO servers
    "NTO",
    # MUC (Multi-User Chat)
    "muc.*", "muc_*", "MUC",
]
