[book]
authors = ["The COSI Maintainers"]
language = "en"
src = "src"
title = "COSI Documentation"

[output.html]
git-repository-url = "https://git.cosi.clarkson.edu/cosi-meta/book"
git-repository-icon = "fas-code-fork"
edit-url-template = "https://git.cosi.clarkson.edu/cosi-meta/book/-/edit/main/{path}"
default-theme = "coal"

[output.html.print]
enable = false
