[book]
authors = ["The COSI Maintainers"]
language = "en"
src = "src"
title = "COSI Documentation"

[output.html]
git-repository-url = "https://git.cosi.clarkson.edu/cosi-meta/book"
edit-url-template = "https://git.cosi.clarkson.edu/cosi-meta/book/-/edit/main/{path}"
git-repository-icon = "fas-code-fork"
default-theme = "coal"
additional-css = ["custom.css"]

[output.html.print]
enable = false
