[book]
authors = ["The COSI Maintainers"]
language = "en"
multilingual = false
src = "src"
title = "COSI Documentation"

[output.html]
git-repository-url = "https://github.com/COSI-Lab/book"
edit-url-template = "https://github.com/COSI-Lab/book/edit/main/{path}"

[output.html.print]
enable = false
