[book]
authors = ["The COSI Maintainers"]
language = "en"
multilingual = false
src = "src"
title = "COSI Documentation"

[output.html]
git-repository-url = "https://gitea.cosi.clarkson.edu/COSI_Maintainers/book"

